### ISSUE TITLE
how to upload multiple image with optional  like user can upload first  and not upload second and upload third one

### ISSUE THREAD

**Issue by MakHiren** [stvnthomas/CodeIgniter-Multi-Upload#11]
how it's possible.
please help..

**Comment by maksumon** [comment]
Add the following code in MY_Upload.php -> public function do_multi_upload($field), right the after the array initialised:

$_FILES[$field]["name"] = array_filter($_FILES[$field]["name"]);

Curtesy: maclau, https://github.com/stvnthomas/CodeIgniter-Multi-Upload/issues/9

**Comment by euphoriatek** [comment]
I have some problem,
 when i upload MY_Upload.php in application->library folder 
and i used in my controller 
                $this->load->library('MY_Upload', $arrConfig);
then it is giving error on runtime 
Fatal error: Class 'CI_Upload' not found in /home/deviis/public_html/project/inventure_project/application/libraries/MY_Upload.php on line 15

how it will sort .
Please help.

**Comment by stvnthomas** [comment]
@euphoriatek You need to load the 'upload' library not 'MY_Upload'.
