### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by dmazlum** [stvnthomas/CodeIgniter-Multi-Upload#12]
Hello,

I am using 2.1.4. But this library doesn't work correctly. Do you have any idea?

Thanks

**Comment by josephrexme** [comment]
I also use 2.1.4 and it works perfectly for me. All you have to do is drop it in your application/libraries folder. You don't even need to do a $this->load->library(). All you'll need to do in your $config[] is to do $config['files'] = ['file1', 'file2', 'file3]. You can paste your code to make me see where you may be getting it wrong
