### ISSUE TITLE
Codeigniter 2.2.0

### ISSUE THREAD

**Issue by simplyniceweb** [stvnthomas/CodeIgniter-Multi-Upload#14]
Please update the codeigniter multi-upload to fit codeigniter 2.2.0!

Thanks!

**Comment by stvnthomas** [comment]
2.2.0 didn't introduce any changes to the Upload library. The current multi-upload library should be fully compatible.

**Comment by simplyniceweb** [comment]
I'll try to reproduce the error again and will email you the error.

On 7/2/14, Steven Thomas notifications@github.com wrote:

> Closed #14.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stvnthomas/CodeIgniter-Multi-Upload/issues/14#event-137091704

## 

Regards,

Jaylord

**Comment by ODelibalta** [comment]
I am getting "Class 'CI_Upload' not found" error. 

$this->load->library('MY_Upload');

I have that in my controller and the MY_Upload file is in the libraries folder in 2.2.0

**Comment by stvnthomas** [comment]
@simplynice25 I just tested 2.2.0 and had no issues.

@ODelibalta Change 'MY_Upload' to 'upload'. Standard syntax is used when using an extended library - see [Extending Native Libraries](http://ellislab.com/codeigniter/user-guide/general/creating_libraries.html) section of the Codeigniter user guide.

**Comment by ODelibalta** [comment]
@stvnthomas That worked... Thank you !

**Comment by simplyniceweb** [comment]
I think you need to update / rename the filename from github.

Thanks for taking this into considerations.

On 7/25/14, Okan Delibalta notifications@github.com wrote:

> @stvnthomas That worked... Thank you !
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stvnthomas/CodeIgniter-Multi-Upload/issues/14#issuecomment-50066001

## 

Regards,

Jaylord
