### ISSUE TITLE
Resize on upload

### ISSUE THREAD

**Issue by christoffwalker** [stvnthomas/CodeIgniter-Multi-Upload#17]
Hi Steven,

I'm attempting to resize the images upon upload, so that I can upload images straight from the camera, where the upload will then resize them to around 1,000 pixels wide, or 600px high.

I have tried both creating thumbnails, and then even forcing the sizes in the MY_Upload library but no joy... Would it better to loop through them in the model instead?

Do you know the best way to achieve this?
Many thanks,
Chris

**Comment by christoffwalker** [comment]
Update: 

I ran a foreach after the `$this->upload->get_multi_upload_data();` and before `return $image_data;` and specified the images sizes in there and seems to be working well:

<pre>
foreach($image_data as $k => $v) {
    $config = array(
        'source_image' => $v['full_path'],
        'maintain_ratio' => TRUE,
        'width' => 1400,
        'height' => 800
    );
    $this->load->library('image_lib', $config);
    $this->image_lib->resize();
}
</pre>

Hope this helps anyone else...

**Comment by christoffwalker** [comment]
This is doesn't quite work... (Darn!)

It does for a single upload, but upload more than one image seems to break it.
Any ideas would be much appreciated...

**Comment by stvnthomas** [comment]
Is there an actual error? Here's a snippet of what I use in one of my models for reference. This loads the image_lib library once outside the loop and the settings are being cleared after each resize.

```
if($this->upload->do_multi_upload("files")){
    $data = $this->upload->get_multi_upload_data();

    $this->load->library("image_lib");
    foreach($data as $file){
        if((int)$file["is_image"] === 1){
            $this->image_lib->initialize(array(
                "width"         => 1280,
                "height"        => 1024,
                "master_dim"    => "width",
                "source_image"  => $file["full_path"]
            ));
            $this->image_lib->resize();
            $this->image_lib->clear();
        }
    }
}
```

**Comment by christoffwalker** [comment]
Hi Steven,

Not getting an error as such, but when I tried multiple images, whilst they still uploaded the first didn't resize and the subsequent image was resized to top-left, with the rest of the image as a black background.

But thanks very much or your snippet, this looks much better, I'll give that a whirl...

**Comment by christoffwalker** [comment]
Your code works a treat, thanks again.
I reckon not having `$this->image_lib->clear();` was partly to blame.
Cheers!

**Comment by christoffwalker** [comment]
Any thoughts on why it's uploading both original and resized?
Ideally just need to resize...

**Comment by christoffwalker** [comment]
Here's my full model code:

<pre>
function do_multi_upload($property_id) {
    $this->load->library('upload');
    // Filenames array
    $filenames_ar = array();
    $i = 0;
    foreach($_FILES['files']['name'] as $k => $v) {
        $rand               = mt_rand(100000,999999);
        $segments           = explode('.', $v);
        $extension          = strtolower(array_pop($segments));
        $name               = "img_{$property_id}_{$rand}.{$extension}";
        $filenames_ar[$k]   = "{$name}";
        $i++;
    }
    $this->upload->initialize(array(
        "upload_path"   => FCPATH.'static/images/uploaded/',
        "file_name"     => $filenames_ar,
        "allowed_types" => 'jpg',
        "max_size"      => '0',
    ));
    
    // stvnthomas
    if(!$this->upload->do_multi_upload("files")) {
        
        $error = array('error' => $this->upload->display_errors());
        return $error;
        
    } else {
        
        if($this->upload->do_multi_upload('files')){
            $image_data = $this->upload->get_multi_upload_data();
            $this->load->library('image_lib');
            foreach($image_data as $file){
                if((int)$file["is_image"] === 1) {
                    $this->image_lib->initialize(array(
                        'source_image'   => $file['full_path'],
                        'maintain_ratio' => TRUE,
                        'width'          => 1400,
                        'height'         => 800,
                        'master_dim'     => 'auto'
                        ));
                    $this->image_lib->resize();
                    $this->image_lib->clear();
                }
            }
        }
        return $image_data;
    }
}
</pre>

**Comment by stvnthomas** [comment]
Sorry for the late reply. I don't initially see anything wrong with your snippet. Hopefully you got it sorted out. This post seems to imply calling clear() before initialize() might fix the problem: https://ellislab.com/forums/viewthread/173145/#865917.
