### ISSUE TITLE
get_multi_upload_data() returns an empty array? 

### ISSUE THREAD

**Issue by ammarjabakji** [stvnthomas/CodeIgniter-Multi-Upload#18]
get_multi_upload_data() returns an empty array? 
Any Help?

**Comment by stvnthomas** [comment]
Are your files uploading? Check your logs for errors.

**Comment by rajasajidmanzoor** [comment]
i have same issue. Files are being uploaded on server. and no warning or error is thrown by compiler but get_multi_upload_data() returns an emtpy array..
