### ISSUE TITLE
How to get All uploaded file names

### ISSUE THREAD

**Issue by rajasajidmanzoor** [stvnthomas/CodeIgniter-Multi-Upload#19]
Hello.
Please tell me how can  i get all uploaded files names in Multi_upload library.
i tried using foreach and for loop but it returns only last uploaded file name in sequence. not the names of all files..
waiting for reply.

Sajid

**Comment by rajasajidmanzoor** [comment]
i tried follwing to get uploaded files name  
                        $upload_data=$this->upload->get_multi_upload_data();
                        echo $upload_data['file_name']."<br/>";

and it gives me error undefined index file_name

**Comment by stvnthomas** [comment]
The get_multi_upload_data() method returns a multidimensional associative array. You can see an example in the readme. To get the filename of your first file it would be

```
$upload_data[0]["file_name"];
```

The second filename would be 

```
$upload_data[1]["file_name"];
```

And so on.

If you want an array of all the filenames you may be able to use array_column(), though I haven't tried it before.

```
$filenames = array_column($upload_data, "file_name");
```
