### ISSUE TITLE
is not working

### ISSUE THREAD

**Issue by ArunprasanthS** [stvnthomas/CodeIgniter-Multi-Upload#2]
my from 

<label>Attach Files</label>
<?php
            $data   = array('name'=>'files[]','multiple'=>'multiple', 'class'=>'span3');
            echo form_upload($data); ?>

and my controller

$this->load->library('upload');

$config['upload_path'] = './uploads/';
        $config['allowed_types'] = 'gif|jpg|png';
        $config['max_size'] = '1000';
        $config['max_width']  = '1024';
        $config['max_height']  = '768';

```
    $this->load->library('upload', $config);

    if ( ! $this->upload->do_upload("files"))
    {
        $error = array('error' => $this->upload->display_errors());

        print_r($error);

        //$this->load->view('upload_form', $error);
    }
    else
    {
        $data = array('upload_data' => $this->upload->data());

        //$this->load->view('upload_success', $data);
        print_r($data);
    }

        exit;
```

i m getting an error like The upload path does not appear to be valid.

if i m removed this line $this->load->library('upload'); and chnaged function do_upload its working..
wat to do?

**Comment by stvnthomas** [comment]
From the code you posted, it doesn't look like you're using any of the multi-upload methods. Look at the readme file to see the correct usage for the multi-upload functionality - specifically how the do_multi_upload() method replaces the do_upload() method.
The path error is likely a separate issue. Check the the path exists (you're using a relative path so it's relative to the root directory). Check that the path is writable.
