### ISSUE TITLE
make file upload optional

### ISSUE THREAD

**Issue by nlemsieh** [stvnthomas/CodeIgniter-Multi-Upload#4]
assuming i have a form with 3 file fields, how can i make just one required and the rest optional ?
thanks

**Comment by stvnthomas** [comment]
The multi-upload option only performs the actual upload of the files, not validation checks, though, perhaps something can be added in in the future for requirement checks. For right now you'd need to do a verification check before performing the upload. Maybe something like this?

```
//Assuming the first file in your multi-upload files is required -
//array key '0' - check if it's missing and if so, produce an error.
if(empty($_FILES["name"][0])){
    //Error.
}

//Otherwise, proceed as normal. Configure upload.
$this->upload->initialize(array(
    //Your configuration.
));

//Perform upload.
if($this->upload->do_multi_upload("files")){
    //Code to run upon successful upload.
}
```
