### ISSUE TITLE
Uploading XLS doesn't work

### ISSUE THREAD

**Issue by oscarromero** [stvnthomas/CodeIgniter-Multi-Upload#6]
I've tried upload an xls file and got "The file type you are attempting to upload is not allowed." I modified the first call for "is_allowed_filetype" method sending as a "true" parameter and then works.

My CI version is 2.1.3

Regards!

**Comment by stvnthomas** [comment]
When getting this error, check your mimetype settings to make sure your file type is being properly reported.
